self.Specific_general_conversion = {'Administration Studies': "Business, Mgt and Public Administration",
    'Art Studies': "Visual & performing Arts, and Comm. Technologies",
    'Aviation': "Physical and Life Sciences and Technologies",
    'Business Studies': "Business, Mgt and Public Administration",
    'Construction': "Architecture and Related Technologies",
    'Design Studies': "Visual & performing Arts, and Comm. Technologies",
    'Economic Studies': "Business, Mgt and Public Administration",
    'Education': 'Education',
    'Energy Studies': "Physical and Life Sciences and Technologies",
    'Engineering Studies': "Engineering",
    'Environmental Studies': "Agriculture, Natural Resources and Conservation",
    'Fashion': "Visual & performing Arts, and Comm. Technologies",
    'Food and Beverage Studies': "Physical and Life Sciences and Technologies",
    'General Studies': "Physical and Life Sciences and Technologies",
    'Health Care': "Nursing",
    'Humanities Studies': "Humanities",
    'Journalism and Mass Communication': "Visual & performing Arts, and Comm. Technologies",
    'Languages': "Visual & performing Arts, and Comm. Technologies",
    'Law Studies': "Law",
    'Life Sciences': "Physical and Life Sciences and Technologies",
    'Management Studies': "Business, Mgt and Public Administration",
    'Marketing Studies': "Business, Mgt and Public Administration",
    'Natural Sciences': "Physical and Life Sciences and Technologies",
    'Performing Arts': "Visual & performing Arts, and Comm. Technologies",
    'Social Sciences': "Humanities",
    'Sport': "Other Health, Parks, Recreation and Fitness",
    'Sustainability Studies': "Agriculture, Natural Resources and Conservation",
    'Technology Studies': "Math, Computer and Information Sciences",
    'Tourism and Hospitality': "Business, Mgt and Public Administration",
    'Transportation and Logistics': "Personal, Protective and Transportation services" 
}
