
dict={"University of Alberta": ['Edmonton'],
"Alberta University of the Arts": ['Edmonton'],
"Grant MacEwan University": ['Edmonton'],
"Athabasca University": ['Athabasca'],
"University of Calgary": ['Calgary'],
"Mount Royal University": ['Calgary'],
"University of Lethbridge": ['Lethbridge'],
"University of British Columbia": ['Vancouver'],
"Capilano University": ['Vancouver'],
"Emily Carr University of Art and Design": ['Vancouver'],
"Simon Fraser University": ['Burnaby'],
"Kwantlen Polytechnic University": ['Surrey'],
"University of Victoria": ['Victoria'],
"Royal Roads University": ['Victoria'],
"University of Northern British Columbia": ['Prince George'],
"Thompson Rivers University": ['Kamloops'],
"Justice Institute of British Columbia": ['New Westminister'],
"Vancouver Island University": ['Nanaimo'],
"University of the Fraser Valley": ['Abbotsford'],
"University of Manitoba": ['Winnipeg'],
"University of Winnipeg": ['Winnipeg'],
"Université de Saint-Boniface": ['Winnipeg'],
"Brandon University": ['Brandon'],
"University of New Brunswick": ['Fredericton'],
"St. Thomas University": ['Fredericton'],
"Mount Allison University": ['Sackville'],
"Université de Moncton": ['Moncton'],
"Memorial University of Newfoundland": ["St. John\'s"],
"Dalhousie University": ['Halifax'],
"Saint Mary's University": ['Halifax'],
"University of King's College": ['Halifax'],
"Mount Saint Vincent University": ['Halifax'],
"NSCAD University": ['Halifax'],
"Acadia University": ['Wolfville'],
"Cape Breton University": ['Sydney'],
"St. Francis Xavier University": ['Antigonish'],
"University of Toronto": ['Toronto'],
"York University": ['Toronto'],
"Toronto Metropolitan University": ['Toronto'],
"University of Ottawa": ['Ottawa'],
"Carleton University": ['Ottawa'],
"McMaster University": ['Hamilton'],
"University of Waterloo": ['Waterloo'],
"Wilfrid Laurier University": ['Waterloo'],
"Western University": ['London'],
"Queen's University": ['Kingston'],
"University of Guelph": ['Guelph'],
"Brock University": ['St. Catharines'],
"Lakehead University": ['Thunder Bay'],
"Trent University": ['Peterborough'],
"Ontario Tech University": ['Oshawa'],
"University of Windsor": ['Windsor'],
"Algoma University": ['Sault Ste. Marie'],
"Nipissing University": ['North Bay'],
"Laurentian University": ['Sudbury'],
"University of Prince Edward Island": ['Charlottetown'],
"McGill University": ['Montreal'],
"Université de Montréal": ['Montreal'],
"Concordia University": ['Montreal'],
"Université Laval": ['Quebec City'],
"Bishop's University": ['Sherbrooke'],
"University of Saskatchewan": ['Saskatoon'],
"University of Regina": ['Regina'],
"Yukon College": ['Whitehorse']}
