list_of_majors = {
    'Administration Studies': ['social studies', 'organizational skills', 'time management', 'leadership', 'problem-solving'],
    'Art Studies': ['art', 'creativity', 'attention to detail', 'adaptability', 'patience'],
    'Aviation': ['mathematics', 'physics', 'creativity', 'attention to detail', 'adaptability', 'patience'],
    'Business Studies': ['economics', 'mathematics', 'attention to detail', 'problem-solving', 'decision-making', 'adaptability', "project management"],
    'Construction': ['mathematics', "teamwork", "problem-solving", "adaptability", "attention to detail", "weather conditions", "outdoor work", "hands-on work", "safety consciousness", "project management"],
    'Design Studies': ['art', "creativity", "attention to detail", "adaptability", "time management"],
    'Economic Studies': ['economics', "analytical skills", "critical thinking", "research", "problem-solving"],
    'Education': ['psychology', "patience", "empathy", "adaptability", "organization"],
    'Energy Studies': ['physics', 'environmental science', "analytical skills", "problem-solving", "attention to detail", "adaptability"],
    'Engineering Studies': ['physics', 'mathematics', "analytical skills", "problem-solving", "attention to detail", "teamwork", "safety consciousness"],
    'Environmental Studies': ['biology', 'environmental science', "critical thinking", "problem-solving", "attention to detail", "adaptability", "safety consciousness"],
    'Fashion': ['art', 'home economics', "creativity", "attention to detail", "adaptability", "time management"],
    'Food and Beverage Studies': ['home economics', "attention to detail", "teamwork", "adaptability", "time management"],
    'General Studies': ['general studies', "critical thinking", "adaptability", "problem-solving", "time management"],
    'Health Care': ['biology', 'chemistry', "empathy", "teamwork", "adaptability", "attention to detail"],
    'Humanities Studies': ['english', 'social studies', "critical thinking", "analytical skills", "research", "adaptability"],
    'Journalism and Mass Communication': ['english', 'media studies', "writing", "adaptability", "time management", "research"],
    'Languages': ['english', 'language courses', "multilingualism", "cultural proficiency", "adaptability", "writing"],
    'Law Studies': ['social studies', 'law', "analytical skills", "critical thinking", "research", "problem-solving"],
    'Life Sciences': ['biology', "analytical skills", "attention to detail", "problem-solving", "research"],
    'Management Studies': ['business studies', "leadership", "analytical skills", "problem-solving", "adaptability", "project management"],
    'Marketing Studies': ['business studies', "creativity", "analytical skills", "adaptability", "time management"],
    'Natural Sciences': ['physics', 'chemistry', 'biology', "analytical skills", "problem-solving", "attention to detail", "research"],
    'Performing Arts': ['art', 'music', 'drama', "creativity", "adaptability", "teamwork", "discipline"],
    'Social Sciences': ['social studies', 'psychology', "analytical skills", "critical thinking", "empathy", "research"],
    'Sport': ['gym', "teamwork", "adaptability", "discipline", "leadership", "physical activity"],
    'Sustainability Studies': ['biology', 'environmental science', "critical thinking", "problem-solving", "attention to detail", "adaptability", "safety consciousness"],
    'Technology Studies': ['physics', 'mathematics', "analytical skills", "problem-solving", "teamwork", "adaptability", "project management"],
    'Tourism and Hospitality': ['business studies', 'geography', "customer service", "adaptability", "teamwork", "time management"],
    'Transportation and Logistics': ['physics', 'mathematics', 'technology studies', "analytical skills", "problem-solving", "attention to detail", "adaptability"]
}

counter = {
    'Administration Studies': 0,
    'Art Studies': 0,
    'Aviation': 0,
    'Business Studies': 0,
    'Construction': 0,
    'Design Studies': 0,
    'Economic Studies': 0,
    'Education': 0,
    'Energy Studies': 0,
    'Engineering Studies': 0,
    'Environmental Studies': 0,
    'Fashion': 0,
    'Food and Beverage Studies': 0,
    'General Studies': 0,
    'Health Care': 0,
    'Humanities Studies': 0,
    'Journalism and Mass Communication': 0,
    'Languages': 0,
    'Law Studies': 0,
    'Life Sciences': 0,
    'Management Studies': 0,
    'Marketing Studies': 0,
    'Natural Sciences': 0,
    'Performing Arts': 0,
    'Social Sciences': 0,
    'Sport': 0,
    'Sustainability Studies': 0,
    'Technology Studies': 0,
    'Tourism and Hospitality': 0,
    'Transportation and Logistics': 0
}

ordered_questions_chars ={
    "Do you enjoy holding leadership roles and leading people?": ["leadership"],
    "Would you consider yourself to be a creative and artistic person?": ["creativity", "artistic"],
    "Do you enjoy problem-solving?": ["problem-solving"],
    "Are you adaptable to new situations?": ["adaptability"],
    "Do you have a keen attention to detail?": ["attention to detail"],
    "Do you possess strong analytical skills?": ["analytical skills"],
    "Are you disciplined and well-organized?": ["discipline"],
    "Do you enjoy conducting research?": ["research"],
    "Do you have good customer service skills?": ["customer service"],
    "Are you multilingual or interested in language courses?": ["multilingualism"],
    "Are you environmentally aware?": ["environmental science", "adaptability"],
    "Do you enjoy collaborating in a team?": ["teamwork"],
    "Are you good at making decisions?": ["decision-making"],
    "Do you manage your time effectively?": ["time management"],
    "Are you patient and empathetic?": ["empathy", "patience"],
    "Do you have a creative mindset?": ["creativity"],
    "Are you interested in legal studies or law-related topics?": ["law"],
    "Do you enjoy physical activities and sports?": ["sport"],
    "Are you interested in arts and culture?": ["arts", "culture"],
    "Do you have a strong interest in technology and innovation?": ["technology"],
    "Are you interested in healthcare and well-being?": ["healthcare"],
    "Do you enjoy writing and communication?": ["writing"],
    "Are you interested in fashion and design?": ["fashion"],
    "Do you enjoy music, drama, or the performing arts?": ["music", "drama"],
    "Are you interested in geography and tourism?": ["geography", "tourism"],
    "Do you have an interest in energy and the environment?": ["energy", "environmental science"],
    "Do you have a general interest in various subjects?": ["general studies"],
    "Are you interested in studying and understanding economic principles?": ["economics", "business studies"],
    "Do you have a knack for understanding and interpreting laws and regulations?": ["law", "analytical skills"],
    "Do you enjoy exploring and experimenting with scientific concepts?": ["physics", "chemistry", "biology", "analytical skills"],
    "Are you passionate about promoting environmental sustainability?": ["environmental science", "sustainability"],
    "Would you like to work on projects that involve creative expression and artistic skills?": ["art", "creativity"],
    "Do you find joy in coordinating and managing various aspects of projects?": ["organization", "time management"],
    "Are you interested in exploring and understanding different cultures and societies?": ["social studies", "multiculturalism"],
    "Do you see yourself excelling in roles that involve leadership and decision-making?": ["leadership", "decision-making"],
    "Would you enjoy working on projects related to technology and innovation?": ["technology", "innovation"],
    "Are you passionate about health and well-being, with an interest in biology and chemistry?": ["healthcare", "biology", "chemistry"],
    "Do you find satisfaction in problem-solving and attention to detail?": ["problem-solving", "attention to detail"],
    "Are you interested in the world of business and its various aspects?": ["business studies", "management"],
    "Do you enjoy creative pursuits in the realm of arts and design?": ["art", "design", "creativity"],
    "Are you fascinated by the natural world and interested in environmental issues?": ["environmental science", "biology"],
    "Do you have a strong interest in the performing arts, including music, drama, and theater?": ["arts", "performing arts"],
    "Are you interested in languages, linguistics, or cultural proficiency?": ["languages", "cultural proficiency"],
    "Do you enjoy teamwork and collaboration in various projects?": ["teamwork", "collaboration"],
    "Are you comfortable working in various weather conditions?": ["weather conditions", "outdoor work"],
    "Do you enjoy working with your hands and being physically active?": ["hands-on work", "physical activity"],
    "Do you pay attention to details and follow safety guidelines diligently?": ["attention to detail", "safety consciousness"],
    }

school_subjects = ["mathematics", "social studies", 'english', 'art',
                    "physics", "chemistry", "biology", "home economics",
                    "music", "drama", "gym"]